// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: kv.proto

#include "kv.pb.h"
#include "kv.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace kv {

static const char* KVService_method_names[] = {
  "/kv.KVService/Login",
  "/kv.KVService/ExecuteSingle",
  "/kv.KVService/ExecuteBatch",
};

std::unique_ptr< KVService::Stub> KVService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< KVService::Stub> stub(new KVService::Stub(channel, options));
  return stub;
}

KVService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Login_(KVService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ExecuteSingle_(KVService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ExecuteBatch_(KVService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status KVService::Stub::Login(::grpc::ClientContext* context, const ::kv::LoginRequest& request, ::kv::LoginResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::kv::LoginRequest, ::kv::LoginResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Login_, context, request, response);
}

void KVService::Stub::async::Login(::grpc::ClientContext* context, const ::kv::LoginRequest* request, ::kv::LoginResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::kv::LoginRequest, ::kv::LoginResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, std::move(f));
}

void KVService::Stub::async::Login(::grpc::ClientContext* context, const ::kv::LoginRequest* request, ::kv::LoginResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::kv::LoginResponse>* KVService::Stub::PrepareAsyncLoginRaw(::grpc::ClientContext* context, const ::kv::LoginRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::kv::LoginResponse, ::kv::LoginRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Login_, context, request);
}

::grpc::ClientAsyncResponseReader< ::kv::LoginResponse>* KVService::Stub::AsyncLoginRaw(::grpc::ClientContext* context, const ::kv::LoginRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLoginRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status KVService::Stub::ExecuteSingle(::grpc::ClientContext* context, const ::kv::SingleRequest& request, ::kv::SingleResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::kv::SingleRequest, ::kv::SingleResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ExecuteSingle_, context, request, response);
}

void KVService::Stub::async::ExecuteSingle(::grpc::ClientContext* context, const ::kv::SingleRequest* request, ::kv::SingleResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::kv::SingleRequest, ::kv::SingleResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ExecuteSingle_, context, request, response, std::move(f));
}

void KVService::Stub::async::ExecuteSingle(::grpc::ClientContext* context, const ::kv::SingleRequest* request, ::kv::SingleResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ExecuteSingle_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::kv::SingleResponse>* KVService::Stub::PrepareAsyncExecuteSingleRaw(::grpc::ClientContext* context, const ::kv::SingleRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::kv::SingleResponse, ::kv::SingleRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ExecuteSingle_, context, request);
}

::grpc::ClientAsyncResponseReader< ::kv::SingleResponse>* KVService::Stub::AsyncExecuteSingleRaw(::grpc::ClientContext* context, const ::kv::SingleRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncExecuteSingleRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status KVService::Stub::ExecuteBatch(::grpc::ClientContext* context, const ::kv::BatchRequest& request, ::kv::BatchResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::kv::BatchRequest, ::kv::BatchResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ExecuteBatch_, context, request, response);
}

void KVService::Stub::async::ExecuteBatch(::grpc::ClientContext* context, const ::kv::BatchRequest* request, ::kv::BatchResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::kv::BatchRequest, ::kv::BatchResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ExecuteBatch_, context, request, response, std::move(f));
}

void KVService::Stub::async::ExecuteBatch(::grpc::ClientContext* context, const ::kv::BatchRequest* request, ::kv::BatchResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ExecuteBatch_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::kv::BatchResponse>* KVService::Stub::PrepareAsyncExecuteBatchRaw(::grpc::ClientContext* context, const ::kv::BatchRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::kv::BatchResponse, ::kv::BatchRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ExecuteBatch_, context, request);
}

::grpc::ClientAsyncResponseReader< ::kv::BatchResponse>* KVService::Stub::AsyncExecuteBatchRaw(::grpc::ClientContext* context, const ::kv::BatchRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncExecuteBatchRaw(context, request, cq);
  result->StartCall();
  return result;
}

KVService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      KVService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< KVService::Service, ::kv::LoginRequest, ::kv::LoginResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](KVService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::kv::LoginRequest* req,
             ::kv::LoginResponse* resp) {
               return service->Login(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      KVService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< KVService::Service, ::kv::SingleRequest, ::kv::SingleResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](KVService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::kv::SingleRequest* req,
             ::kv::SingleResponse* resp) {
               return service->ExecuteSingle(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      KVService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< KVService::Service, ::kv::BatchRequest, ::kv::BatchResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](KVService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::kv::BatchRequest* req,
             ::kv::BatchResponse* resp) {
               return service->ExecuteBatch(ctx, req, resp);
             }, this)));
}

KVService::Service::~Service() {
}

::grpc::Status KVService::Service::Login(::grpc::ServerContext* context, const ::kv::LoginRequest* request, ::kv::LoginResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status KVService::Service::ExecuteSingle(::grpc::ServerContext* context, const ::kv::SingleRequest* request, ::kv::SingleResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status KVService::Service::ExecuteBatch(::grpc::ServerContext* context, const ::kv::BatchRequest* request, ::kv::BatchResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace kv

